services:
  - type: web
    name: keybounce
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Set these in the Render dashboard with your real secrets/URIs
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
